#!/bin/sh

echo "this script will automatically set up arch (UEFI), mostly following the official install guide, but with some tweaks/packages of mine installed too"

echo "this script should be run after you've chroot-ed into your install and have done all previous steps from the install guide"

timedatectl list-timezones | column

echo "choose a timezone from the list above, format: Region/City"

read timezone

ln -sf /usr/share/zoneinfo/$timezone /etc/localtime

hwclock --systohc

sed -i '177s/.//' /etc/locale.gen # credit to ermannoferrari for this

locale-gen

echo "LANG=en_US.UTF-8" >> /etc/locale.conf

echo "what should the hostname be?"

read hostname

echo "$hostname" >> /etc/hostname

echo "127.0.0.1	localhost" >> /etc/hosts
echo "::1	localhost" >> /etc/hosts
echo "127.0.1.1	$hostname.localdomain	$hostname" >> /etc/hosts

echo "installing networkmanager..." && sleep 5

pacman -S --needed --noconfirm networkmanager

systemctl enable NetworkManager

echo "what should the root password be?"

passwd

echo "what cpu do you have? (intel/amd)"

read cpu

if [ "$cpu" = "intel" ]; then
    pacman -S --needed --noconfirm intel-ucode
elif [ "$cpu" = "amd" ]; then
    pacman -S --needed --noconfirm amd-ucode
else
    echo "accepted answers are intel/amd"
fi

echo "where is the ESP mounted? example: /boot/efi"

read esp

echo "installing grub..." && sleep 5

pacman -S --needed --noconfirm grub efibootmgr

grub-install --target=x86_64-efi --efi-directory=$esp --bootloader-id=GRUB

grub-mkconfig -o /boot/grub/grub.cfg

echo "list any additional packages you want installed in a space separated list, e.g. (htop neofetch ...)"

read pkgs

echo "installing additional packages..." && sleep 5

pacman -S expac

# this gets the latest installed kernel package so we can install its headers package
# yes ik this is probably wonky asf but its what i could come up with :D

krnl="$(expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort -n | awk '{print $3}' | grep '^linux' | sed '/linux-firmware\|.-headers/d' | tail -n1)"

pacman -S --needed --noconfirm base-devel $krnl-headers man-db man-pages texinfo $pkgs

echo "what should the name of the your user be?"

read name

useradd -m $name

echo "what should his password be?"

passwd $name

echo "$name ALL=(ALL) ALL" >> /etc/sudoers.d/$name # also credit to ermannoferrari for this

echo "cleaning up..." && sleep 5

pacman -Rns --noconfirm expac

echo "install finished, exit the chroot, unmount and reboot"
